/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package designPatterns;

import designPatterns.solidPrinciples.openClose.App;
import org.testng.annotations.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
